eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:9102/eureka/

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
      springframework:
        security: DEBUG

spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/cart_service?useSSL=false&allowPublicKeyRetrieval=true
    username: root
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: false
    show-sql: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/starshipshop-realm
  sleuth:
    sampler:
      probability: 1.0
  sql:
    init:
      mode: always
      platform: mysql
  zipkin:
    base-url: http://localhost:9411
