server:
  port: 9102

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  username: ${EUREKA_USERNAME:eureka}
  password: ${EUREKA_PASSWORD:password}

spring:
  cloud:
    config:
      import-check:
        enabled: false