server:
  port: 9102

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  username: ${EUREKA_USERNAME:eureka}
  password: ${EUREKA_USERNAME:password}

spring:
  cloud:
    config:
      import-check:
        enabled: false
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411