server:
  port: 9102

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  username: eureka
  password: password

spring:
  cloud:
    config:
      import-check:
        enabled: false