eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:9102/eureka/

spring:
  cloud:
    gateway:
      routes:
      - id: product-service
        uri: lb://product-service
        predicates:
          - Path=/api/v1/products/starship/{skuCode}
          - Method=GET
      - id: discovery-server
        uri: http://localhost:9102/
        predicates:
          - Path=/eureka/web
        filters:
          - SetPath=/
      - id: discovery-server-static
        uri: http://localhost:9102/
        predicates:
          - Path=/eureka/**
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: starshipshop-provider
            client-id: spring-gateway-client
            client-secret: hjHJ00PSt7kgglPdY1ixJbI6qUcTHzlS
            authorization-grant-type: authorization_code
            redirect-uri: 'http://localhost:9103/login/oauth2/code/{registrationId}'
        provider:
          starshipshop-provider:
            issuer-uri: http://localhost:8181/realms/starshipshop-realm
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
