eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9102/eureka/

spring:
  cloud:
    gateway:
      routes:
      - id: product-service
        uri: lb://product-service
        predicates:
          - Path=/api/v1/product/starship/{skuCode}
