app:
  hashids:
    salt: mySuperSalt
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
      springframework:
        security: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9102/eureka/

spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/inventory_service?useSSL=false&allowPublicKeyRetrieval=true
    username: root
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: false
    show-sql: false
  sql:
    init:
      mode: always
      platform: mysql
