client:
  starship:
    username: admin@mail.com
    password: password

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:9102/eureka/

#management:
#  endpoint:
#    health:
#      show-details: always
#  endpoints:
#    web:
#      exposure:
#        include: *
#  health:
#    circuitbreakers:
#      enabled: true

#Resilience4j Properties
resilience4j:
  circuitbreaker:
    instances:
      inventory:
        registerHealIndicator: true
        event-consumer-buffer-size: 10
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/product_service?useSSL=false&allowPublicKeyRetrieval=true
    username: root
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: false
    show-sql: false
  sleuth:
    sampler:
      probability: 1.0
  sql:
    init:
      mode: always
      platform: mysql
  zipkin:
    base-url: http://localhost:9411

